CC = g++
CFLAGS = -std=c++17 -Werror -Wextra -Wall
TFLAGS = -lgtest -lpthread -lgtest_main
CFILES = $(wildcard *.cc)
TFILES = $(wildcard *test.cc)

all: test
	
test: $(CFILES)

$(CFILES): 

s21_graph:

clean:
	rm -rf *.out
